async function imagineCommand(sock, chatId, message) {
    try {
        const text = (message.message?.conversation || message.message?.extendedTextMessage?.text || '').slice(8).trim();
        if (!text) return sock.sendMessage(chatId, { text: '❌ Provide a prompt. Example: .imagine a beautiful sunset' }, { quoted: message });
        await sock.sendMessage(chatId, { react: { text: '🎨', key: message.key } });
        const url = `https://image.pollinations.ai/prompt/${encodeURIComponent(text)}?width=512&height=512&nologo=true`;
        await sock.sendMessage(chatId, { image: { url }, caption: `🎨 *${text}*\n\nGenerated by MARCO MALIK & SYED-MD MINI BOT` }, { quoted: message });
    } catch (e) { await sock.sendMessage(chatId, { text: '❌ Failed to generate image.' }, { quoted: message }); }
}
module.exports = imagineCommand;
